name: ask_server

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  alfred:
  json_annotation:
  dbcrypt: ^2.0.0
  corsac_jwt: ^1.0.0-nullsafety.1
  get_it: ^7.2.0
  mongo_dart: ^0.8.1

dev_dependencies:
  build_runner:
  json_serializable:
  test:
  http:
  analyzer: ^5.2.0

# sudo /Users/bohdan.martynov/sdk/flutter_3.3.9/bin/cache/dart-sdk/bin/dart run build_runner build

