name: ask_server

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  alfred:
  json_annotation:
  dbcrypt: ^1.0.0
  corsac_jwt: ^0.4.0
  get_it: ^7.2.0

dev_dependencies:
  build_runner:
  json_serializable:
